version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
